# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sciencepaper', '0001_initial'), ('sciencepaper', '0002_auto_20160407_1107'), ('sciencepaper', '0003_paper_lead_author'), ('sciencepaper', '0004_auto_20160602_1309')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('homepage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('doi', models.CharField(blank=True, max_length=500, null=True)),
                ('journal_name', models.CharField(blank=True, max_length=500, null=True)),
                ('journal_volume', models.IntegerField(blank=True, null=True)),
                ('journal_number', models.IntegerField(blank=True, null=True)),
                ('journal_pages', models.CharField(blank=True, max_length=500, null=True)),
                ('first_published', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='sciencepaper.Author')),
                ('lead_author', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
