# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencepaper', '0002_auto_20160407_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='lead_author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
