# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencepaper', '0003_paper_lead_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
