# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 08:50
from __future__ import unicode_literals

from django.db import migrations
import isi_mip.pages.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_create_initial_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpage',
            name='for_modelers',
            field=wagtail.wagtailcore.fields.StreamField((('faq', wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.CharBlock()), ('answer', wagtail.wagtailcore.blocks.RichTextBlock())))),)),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='for_researchers',
            field=wagtail.wagtailcore.fields.StreamField((('faq', wagtail.wagtailcore.blocks.StructBlock((('question', wagtail.wagtailcore.blocks.CharBlock()), ('answer', wagtail.wagtailcore.blocks.RichTextBlock())))),)),
        ),
        migrations.AlterField(
            model_name='gettingstartedpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('input_data', wagtail.wagtailcore.blocks.StructBlock((('description', wagtail.wagtailcore.blocks.RichTextBlock()),))), ('contact', wagtail.wagtailcore.blocks.StructBlock((('description', wagtail.wagtailcore.blocks.RichTextBlock()), ('sectors', wagtail.wagtailcore.blocks.ListBlock(isi_mip.pages.blocks.SectorBlock))))))),
        ),
    ]
