# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 13:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homepage_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='teaser',
            field=wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('text', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('link', wagtail.wagtailcore.blocks.PageChooserBlock(required=True)))),
        ),
    ]
