# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:41
from __future__ import unicode_literals

from django.db import migrations
import isi_mip.contrib.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160420_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('row', wagtail.wagtailcore.blocks.StreamBlock((('teaser', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('link', wagtail.wagtailcore.blocks.PageChooserBlock(required=True))))), ('bigteaser', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subtitle', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('external_link', wagtail.wagtailcore.blocks.URLBlock(help_text='Will be ignored if an internal link is provided', required=False)), ('internal_link', wagtail.wagtailcore.blocks.PageChooserBlock(help_text='If set, this has precedence over the external link.', required=False)), ('from_date', wagtail.wagtailcore.blocks.DateBlock(required=False)), ('to_date', wagtail.wagtailcore.blocks.DateBlock(required=False))))), ('blog', wagtail.wagtailcore.blocks.StructBlock((('blog_index', isi_mip.contrib.blocks.SpecificPageChooserBlock(help_text='Select blog index page.', required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(help_text='Per default, the title of the blog index will be used.', required=False)), ('entry_count', isi_mip.contrib.blocks.IntegerBlock(default=4, help_text='How many blog entries should be displayed?', max_value=5, min_value=1, required=True))))), ('numbers', wagtail.wagtailcore.blocks.StructBlock((('number1', wagtail.wagtailcore.blocks.StructBlock((('number', wagtail.wagtailcore.blocks.CharBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock())))), ('number2', wagtail.wagtailcore.blocks.StructBlock((('number', wagtail.wagtailcore.blocks.CharBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock()), ('text', wagtail.wagtailcore.blocks.CharBlock()))))))), ('twitter', wagtail.wagtailcore.blocks.StructBlock((('username', wagtail.wagtailcore.blocks.CharBlock(help_text='You will find username and widget_id @ https://twitter.com/settings/widgets/', required=True)), ('widget_id', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('tweet_limit', wagtail.wagtailcore.blocks.CharBlock(max_length=2, required=True)))))))),)),
        ),
    ]
