# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('pages', '0006_auto_20160330_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='teaser',
        ),
        migrations.AddField(
            model_name='homepage',
            name='teaser_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='teaser_text',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='teaser_title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
