# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20160330_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='teaser_link',
            new_name='teaser_link_internal',
        ),
        migrations.AddField(
            model_name='homepage',
            name='teaser_link_external',
            field=models.URLField(blank=True, help_text='Will be ignored if a Link page is provided', verbose_name='External link'),
        ),
    ]
