# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20160330_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='teaser_link_external',
            field=models.URLField(blank=True, help_text='Will be ignored if an internal link is provided', verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='teaser_link_internal',
            field=models.ForeignKey(blank=True, help_text='If set, this has precedence over the external link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Or internal link'),
        ),
    ]
