# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 16:42
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import isi_mip.contrib.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtail.wagtailsnippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20160330_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('teasers', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('link', wagtail.wagtailcore.blocks.PageChooserBlock(required=True)))), template='widgets/listblock.html')), ('bigteaser', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subtitle', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('picture', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('link_external', wagtail.wagtailcore.blocks.URLBlock(help_text='Will be ignored if an internal link is provided', required=False)), ('link_internal', wagtail.wagtailcore.blocks.PageChooserBlock('Or internal link', help_text='If set, this has precedence over the external link.', required=False)), ('from_date', wagtail.wagtailcore.blocks.DateBlock(required=False)), ('to_date', wagtail.wagtailcore.blocks.DateBlock(required=False))))), ('news', wagtail.wagtailcore.blocks.StructBlock((('blog_category', wagtail.wagtailsnippets.blocks.SnippetChooserBlock(help_text='Filter blog by this category', required=False, target_model=blog.models.BlogCategory)), ('entry_count', isi_mip.contrib.blocks.IntegerBlock(help_text='How many blog entries should be displayed?', required=False))))))),
        ),
    ]
