# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_formpage_button_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodelspage',
            name='private_model_message',
            field=models.TextField(default='Your Model is currently not publicly visible. Please review your model details and contact info@isimip.org to make your model public.'),
            preserve_default=False,
        ),
    ]
