# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 11:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_dashboardpage_private_model_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardpage',
            name='private_model_message',
        ),
        migrations.AddField(
            model_name='dashboardpage',
            name='impact_models_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
