# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_dashboardpage_show_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_toc',
            field=models.BooleanField(default=False, help_text='Show Table of Contents'),
        ),
    ]
