# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20171109_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_subject',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Confirmation email subject'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='confirmation_email_text',
            field=models.TextField(blank=True, default='The form was submitted successfully. We will get back to you soon.', null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='send_confirmation_email',
            field=models.BooleanField(default=False, verbose_name='Send confirmation email'),
        ),
    ]
