# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20171123_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='confirmation_email_subject',
            field=models.CharField(blank=True, default='ISIMIP Form submission confirmation.', max_length=500, null=True, verbose_name='Confirmation email subject'),
        ),
    ]
