# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0085_auto_20180215_1105'),
        ('pages', '0030_auto_20181115_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpage',
            name='sectors',
            field=models.ManyToManyField(blank=True, null=True, to='climatemodels.Sector'),
        ),
        migrations.AddField(
            model_name='paperpage',
            name='simulation_rounds',
            field=models.ManyToManyField(blank=True, null=True, to='climatemodels.SimulationRound'),
        ),
    ]
