# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20181119_1527'),
        ('pages', '0032_auto_20181114_1549'),
    ]

    operations = [
    ]
