# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 15:11
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20181205_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperpage',
            name='sectors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='climatemodels.Sector'),
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='simulation_rounds',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='climatemodels.SimulationRound'),
        ),
    ]
