# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20181206_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperpage',
            name='picture',
        ),
    ]
