# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0077_auto_20170301_1209'),
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='involved',
            field=models.ManyToManyField(blank=True, related_name='impact_model_involved', to='climatemodels.BaseImpactModel'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='impact_model_owner', to='climatemodels.BaseImpactModel'),
        ),
    ]
