# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_auto_20170425_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='involved',
            field=models.ManyToManyField(blank=True, related_name='impact_model_involved', to='climatemodels.ImpactModel'),
        ),
    ]
