# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-05 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0004_auto_20170426_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
