# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0005_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_in_participant_list',
            field=models.BooleanField(default=True),
        ),
    ]
