# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Site = apps.get_model("sites", "Site")
    Site.objects.all().delete()
    Site.objects.create(
        id=settings.SITE_ID,
        domain="isi-mip.org",
        name="ISI MIP"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site_forward)
    ]
