# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('institute', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='impactmodel',
            name='contact_person_email',
        ),
        migrations.RemoveField(
            model_name='impactmodel',
            name='contact_person_institute',
        ),
        migrations.RemoveField(
            model_name='impactmodel',
            name='contact_person_name',
        ),
        migrations.AddField(
            model_name='impactmodel',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ContactPerson'),
        ),
    ]
