# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0002_auto_20160308_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactmodel',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='contactperson',
            name='impact_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ImpactModel'),
        ),
    ]
