# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0002_auto_20160228_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencepaper',
            name='climate_model',
        ),
        migrations.AddField(
            model_name='general',
            name='additional_papers',
            field=models.ManyToManyField(blank=True, to='climatemodels.ReferencePaper'),
        ),
        migrations.AlterField(
            model_name='general',
            name='main_reference_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_ref', to='climatemodels.ReferencePaper'),
        ),
    ]
