# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0003_auto_20160308_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='version',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Model Version'),
        ),
    ]
