# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0004_referencepaper_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Water (global)', 'Water (global)'), ('Water (regional)', 'Water (regional)'), ('Biomes', 'Biomes'), ('Forests', 'Forests'), ('Marine Ecosystems and Fisheries (global)', 'Marine Ecosystems and Fisheries (global)'), ('Marine Ecosystems and Fisheries (regional)', 'Marine Ecosystems and Fisheries (regional)'), ('Biodiversity', 'Biodiversity'), ('Health', 'Health'), ('Coastal Infrastructure', 'Coastal Infrastructure'), ('Permafrost', 'Permafrost')], default='Water (global)', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='general',
            unique_together=set([('name', 'sector')]),
        ),
    ]
