# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0005_auto_20160229_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InputPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='climatedataset',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='referencepaper',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='socioeconomicinputvariables',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='data_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ClimateDataSet'),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ClimateDataType'),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.InputPhase'),
        ),
    ]
