# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0006_auto_20160301_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('Water (global)', 'Water (global)'), ('Water (regional)', 'Water (regional)'), ('Biomes', 'Biomes'), ('Forests', 'Forests'), ('Marine Ecosystems and Fisheries (global)', 'Marine Ecosystems and Fisheries (global)'), ('Marine Ecosystems and Fisheries (regional)', 'Marine Ecosystems and Fisheries (regional)'), ('Biodiversity', 'Biodiversity'), ('Health', 'Health'), ('Coastal Infrastructure', 'Coastal Infrastructure'), ('Permafrost', 'Permafrost')], max_length=500)),
                ('data', models.DateField()),
                ('drivers', models.ManyToManyField(to='climatemodels.ClimateDataSet')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.General')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='outputdata',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.Scenario'),
        ),
    ]
