# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0006_auto_20160330_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomes',
            name='evapotranspiration_approaches',
        ),
        migrations.AddField(
            model_name='biomes',
            name='evapotranspiration_approach',
            field=models.TextField(blank=True, null=True, verbose_name='Evapo-transpiration approach'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='considerations',
            field=models.TextField(blank=True, help_text='Things to consider, when calculating basic variables such as GPP, NPP, RA, RH from the model.', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='light_utilization',
            field=models.TextField(blank=True, help_text='photosynthesis, RUE- approach?', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='list_of_pfts',
            field=models.TextField(blank=True, help_text='Provide a list of PFTs using the folllowing format: <pft1_long_name> (<pft1_short_name>); <pft2_long_name> (<pft2_short_name>). Include long name in brackets if no short name is available.', null=True, verbose_name='List of PFTs'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_harvest',
            field=models.TextField(blank=True, help_text='1: crops, 2: harvest from forest management, 3: harvest from grassland management', null=True, verbose_name='Harvest'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_landuse_change',
            field=models.TextField(blank=True, help_text='Deforestation, harvest and other land-use changes', null=True, verbose_name='Land-use change'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_other',
            field=models.TextField(blank=True, null=True, verbose_name='Other processes'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='output',
            field=models.TextField(blank=True, help_text='Is output (e.g. PFT cover) written out per grid-cell area or per land and water area within a grid cell, or land only?', null=True, verbose_name='Output format'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='output_per_pft',
            field=models.TextField(blank=True, help_text='Is output per PFT per unit area of that PFT, i.e. requiring weighting by the fractional coverage of each PFT to get the gridbox average?', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='rooting_depth_differences',
            field=models.TextField(blank=True, help_text='Include how it changes.', null=True, verbose_name='Differences in rooting depth'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='soil_moisture_surface_temperature_coupling',
            field=models.TextField(blank=True, null=True, verbose_name='Coupling/feedback between soil moisture and surface temperature'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='impact_types_energy_demand',
            field=models.TextField(blank=True, null=True, verbose_name='Energy demand (heating & cooling)'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='impact_types_temperature_effects_on_thermal_power',
            field=models.TextField(blank=True, null=True, verbose_name='Temperature effects on thermal power'),
        ),
        migrations.AlterField(
            model_name='marineecosystems',
            name='fishbase_used_for_mass_length_conversion',
            field=models.TextField(blank=True, null=True, verbose_name='Is FishBase used for mass-length conversion?'),
        ),
    ]
