# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0007_auto_20160330_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='vegetation_presentation',
            new_name='vegetation_representation',
        ),
        migrations.AlterField(
            model_name='water',
            name='calibration',
            field=models.BooleanField(default=False, verbose_name='Was the model calibrated?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='water',
            name='vegetation',
            field=models.BooleanField(default=False, verbose_name='Is CO2 fertilisation accounted for?'),
            preserve_default=False,
        ),
    ]
