# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0008_auto_20160330_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='calibration',
            field=models.BooleanField(default=False, verbose_name='Was the model calibrated?'),
        ),
        migrations.AlterField(
            model_name='water',
            name='vegetation',
            field=models.BooleanField(default=False, verbose_name='Is CO2 fertilisation accounted for?'),
        ),
    ]
