# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0009_auto_20160330_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='spin_up',
            field=models.NullBooleanField(choices=[(None, '---------'), (True, 'Yes'), (False, 'No')], help_text='`No` indicates the simulations were run starting in the first reporting year 1971', verbose_name='Did you spin-up your model?'),
        ),
    ]
