# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciencepaper', '0001_initial'),
        ('climatemodels', '0010_auto_20160331_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencepaper',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='referencepaper',
            name='id',
        ),
        migrations.RemoveField(
            model_name='referencepaper',
            name='name',
        ),
        migrations.AddField(
            model_name='referencepaper',
            name='paper_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sciencepaper.Paper'),
            preserve_default=False,
        ),
    ]
