# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 14:30
from __future__ import unicode_literals

from django.db import migrations
import isi_mip.choiceorotherfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0011_auto_20160407_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='resolution',
            field=isi_mip.choiceorotherfield.models.ChoiceOrOtherField(blank=True, choices=[('0.5°x0.5°', '0.5°x0.5°')], help_text='The spatial resolution at which the ISIMIP simulations were run, if on a regular grid. Data was provided on a 0.5°x0.5° grid', max_length=500, null=True, verbose_name='Spatial Resolution'),
        ),
    ]
