# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0012_auto_20160411_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineEcosystemsRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defining_features', models.TextField(blank=True, null=True, verbose_name='Defining features')),
                ('spatial_scale', models.TextField(blank=True, null=True, verbose_name='Spatial scale')),
                ('spatial_resolution', models.TextField(blank=True, null=True, verbose_name='Spatial resolution')),
                ('temporal_scale', models.TextField(blank=True, null=True, verbose_name='Temporal scale')),
                ('temporal_resolution', models.TextField(blank=True, null=True, verbose_name='Temporal resolution')),
                ('taxonomic_scope', models.TextField(blank=True, null=True, verbose_name='Taxonomic scope')),
                ('vertical_resolution', models.TextField(blank=True, null=True, verbose_name='Vertical resolution')),
                ('spatial_dispersal_included', models.TextField(blank=True, null=True, verbose_name='Spatial dispersal included')),
                ('fishbase_used_for_mass_length_conversion', models.TextField(blank=True, null=True, verbose_name='Is FishBase used for mass-length conversion?')),
                ('impact_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ImpactModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technological_progress', models.TextField(blank=True, help_text='Does the model account for GDP changes and technological progress? If so, how are these integrated into the runs?', null=True)),
                ('soil_layers', models.TextField(blank=True, help_text='How many soil layers are used? Which qualities do they have?', null=True)),
                ('water_use', models.TextField(blank=True, help_text='Which types of water use are included?', null=True, verbose_name='Water-use types')),
                ('water_sectors', models.TextField(blank=True, help_text='For the global-water-model varsoc and pressoc runs, which water sectors were included? E.g. irrigation, domestic, manufacturing, electricity, livestock.', null=True, verbose_name='Water-use sectors')),
                ('routing', models.TextField(blank=True, help_text='How is runoff routed?', null=True, verbose_name='Runoff routing')),
                ('routing_data', models.TextField(blank=True, help_text='Which routing data are used?', null=True)),
                ('land_use', models.TextField(blank=True, help_text='Which land-use change effects are included?', null=True, verbose_name='Land-use change effects')),
                ('dams_reservoirs', models.TextField(blank=True, help_text='Describe how are dams and reservoirs are implemented', null=True, verbose_name='Dams & Reservoirs')),
                ('calibration', models.BooleanField(default=False, verbose_name='Was the model calibrated?')),
                ('calibration_years', models.TextField(blank=True, null=True, verbose_name='Which years were used for calibration?')),
                ('calibration_dataset', models.TextField(blank=True, help_text='E.g. WFD, GSWP3', null=True, verbose_name='Which dataset was used for calibration?')),
                ('calibration_catchments', models.TextField(blank=True, null=True, verbose_name='How many catchments were callibrated?')),
                ('vegetation', models.BooleanField(default=False, verbose_name='Is CO2 fertilisation accounted for?')),
                ('vegetation_representation', models.TextField(blank=True, null=True, verbose_name='How is vegetation represented?')),
                ('methods_evapotraspiration', models.TextField(blank=True, null=True, verbose_name='Potential evapotraspiration')),
                ('methods_snowmelt', models.TextField(blank=True, null=True, verbose_name='Snow melt')),
                ('impact_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ImpactModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='MarineEcosystems',
            new_name='MarineEcosystemsGlobal',
        ),
        migrations.RenameModel(
            old_name='Water',
            new_name='WaterGlobal',
        ),
    ]
