# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0015_auto_20160419_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatevariable',
            old_name='abbrevation',
            new_name='abbreviation',
        ),
    ]
