# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0016_auto_20160420_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputdata',
            name='scenario',
        ),
        migrations.AddField(
            model_name='outputdata',
            name='scenarios',
            field=models.ManyToManyField(to='climatemodels.Scenario'),
        ),
        migrations.RemoveField(
            model_name='inputdata',
            name='scenario',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatemodels.Scenario'),
        ),
    ]
