# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0019_inputdata_download_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactmodel',
            old_name='resolution',
            new_name='spatial_resolution',
        ),
    ]
