# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0020_auto_20160426_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Agro-Economic Modelling', 'Agro-Economic Modelling'), ('Biodiversity', 'Biodiversity'), ('Biomes', 'Biomes'), ('Coastal Infrastructure', 'Coastal Infrastructure'), ('Computable General Equilibrium Modelling', 'Computable General Equilibrium Modelling'), ('Energy', 'Energy'), ('Forests', 'Forests'), ('Health', 'Health'), ('Marine Ecosystems and Fisheries (global)', 'Marine Ecosystems and Fisheries (global)'), ('Marine Ecosystems and Fisheries (regional)', 'Marine Ecosystems and Fisheries (regional)'), ('Permafrost', 'Permafrost'), ('Water (global)', 'Water (global)'), ('Water (regional)', 'Water (regional)')], max_length=500),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='spin_up',
            field=models.NullBooleanField(choices=[(None, '---------'), (True, 'Yes'), (False, 'No')], help_text="'No' indicates the simulations were run starting in the first reporting year 1971", verbose_name='Did you spin-up your model?'),
        ),
        migrations.AlterField(
            model_name='outputdata',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Agro-Economic Modelling', 'Agro-Economic Modelling'), ('Biodiversity', 'Biodiversity'), ('Biomes', 'Biomes'), ('Coastal Infrastructure', 'Coastal Infrastructure'), ('Computable General Equilibrium Modelling', 'Computable General Equilibrium Modelling'), ('Energy', 'Energy'), ('Forests', 'Forests'), ('Health', 'Health'), ('Marine Ecosystems and Fisheries (global)', 'Marine Ecosystems and Fisheries (global)'), ('Marine Ecosystems and Fisheries (regional)', 'Marine Ecosystems and Fisheries (regional)'), ('Permafrost', 'Permafrost'), ('Water (global)', 'Water (global)'), ('Water (regional)', 'Water (regional)')], max_length=500),
        ),
    ]
