# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models


def  cleanup_climatevariables(apps, schema_editor):
    ClimateVariable = apps.get_model('climatemodels.ClimateVariable')
    vars = ClimateVariable.objects.all()
    dingsset = set()
    for var in vars:
        if var.name in dingsset:
            var.delete()
        else:
            dingsset.add(var.name)

class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0021_auto_20160503_2054'),
    ]

    operations = [
        migrations.RunPython(cleanup_climatevariables),
    ]
