# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0022_delete_dups_20160510_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatevariable',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='socioeconomicinputvariables',
            options={'verbose_name': 'Socio-economic input variable'},
        ),
        migrations.AlterField(
            model_name='climatevariable',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='version',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Model version'),
        ),
    ]
