# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0023_auto_20160510_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='climatedatatype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='impactmodel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='inputdata',
            options={'ordering': ('name',), 'verbose_name_plural': 'Input data'},
        ),
        migrations.AlterModelOptions(
            name='inputphase',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='outputdata',
            options={'verbose_name': 'Output data', 'verbose_name_plural': 'Output data'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='simulationround',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='socioeconomicinputvariables',
            options={'ordering': ('name',), 'verbose_name': 'Socio-economic input variable'},
        ),
        migrations.AlterModelOptions(
            name='spatialaggregation',
            options={'ordering': ('name',)},
        ),
    ]
