# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0025_auto_20160527_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodel',
            name='spatial_aggregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatemodels.SpatialAggregation'),
        ),
    ]
