# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0026_impactmodel_spatial_aggregation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='main_reference_paper',
            field=models.ForeignKey(blank=True, help_text='The single paper that should be cited when referring to simulation output from this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_ref', to='climatemodels.ReferencePaper', verbose_name='Reference paper: main reference'),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='spatial_aggregation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemodels.SpatialAggregation'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='data_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemodels.ClimateDataType'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemodels.InputPhase'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemodels.Scenario'),
        ),
        migrations.AlterField(
            model_name='outputdata',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemodels.ImpactModel'),
        ),
    ]
