# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0027_auto_20160602_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodel',
            name='climate_variables_info',
            field=models.TextField(blank=True, help_text='Including how variables were derived that were not included in the ISIMIP input data', verbose_name='Additional climate variables information'),
        ),
        migrations.AddField(
            model_name='impactmodel',
            name='spatial_resolution_info',
            field=models.TextField(blank=True, help_text='Anything else necessary to understand the spatial aggregation and resolution at which the model operates', verbose_name='Additional spatial aggregation & resolution information'),
        ),
        migrations.AddField(
            model_name='impactmodel',
            name='temporal_resolution_info',
            field=models.TextField(blank=True, verbose_name='Additional temporal resolution information'),
        ),
    ]
