# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0028_auto_20160609_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodel',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='temporal_resolution_info',
            field=models.TextField(blank=True, help_text='Anything else necessary to understand the temporal resolution at which the model operates', verbose_name='Additional temporal resolution information'),
        ),
    ]
