# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:04
from __future__ import unicode_literals

from django.db import migrations


def migrate_owner_to_owners(apps, schema_editor):
    ims = apps.get_model('climatemodels', 'ImpactModel').objects.all()
    for im in ims:
        im.owners.add(im.owner)
        im.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0030_auto_20160712_1300'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_to_owners),
    ]
