# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0031_auto_20160712_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactmodel',
            name='owner',
        ),
    ]
