# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def move_data_to_base_impact_model(apps, schema_editor):
    ImpactModel = apps.get_model('climatemodels', 'ImpactModel')
    for impact_model in ImpactModel.objects.all():
        impact_model.simulation_round = impact_model.simulation_round_new
        impact_model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0035_auto_20170111_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impactmodel',
            options={'ordering': ('base_model', 'simulation_round')},
        ),
        migrations.AddField(
            model_name='impactmodel',
            name='simulation_round',
            field=models.ForeignKey(blank=True, help_text='The ISIMIP simulation round for which these model details are relevant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemodels.SimulationRound'),
        ),
        migrations.AlterUniqueTogether(
            name='impactmodel',
            unique_together=set([('base_model', 'simulation_round')]),
        ),
        # save old data before removing fields
        migrations.RunPython(
            move_data_to_base_impact_model
        ),
        migrations.RemoveField(
            model_name='impactmodel',
            name='simulation_round_new',
        ),
    ]
