# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0042_auto_20170112_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseimpactmodel',
            options={'ordering': ('name', 'sector')},
        ),
        migrations.AddField(
            model_name='climatedatatype',
            name='is_climate_data_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='spin_up',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], help_text="'No' indicates the simulations were run starting in the first reporting year 1971", verbose_name='Was a spin-up performed?'),
        ),
    ]
