# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0043_auto_20170116_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClimateDataType',
            new_name='DataType',
        ),
    ]
