# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_contact_persons(apps, schema_editor):
    ContactPersonModel = apps.get_model('climatemodels', 'ContactPerson')
    for cp in ContactPersonModel.objects.all():
        cp.base_impact_model = cp.impact_model.base_model
        cp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0044_auto_20170116_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='base_impact_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatemodels.BaseImpactModel'),
        ),
        migrations.RunPython(
            set_contact_persons
        ),
    ]
