# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0045_contactperson_base_impact_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactperson',
            name='impact_model',
        ),
        migrations.AddField(
            model_name='impactmodel',
            name='responsible_person',
            field=models.CharField(blank=True, help_text='Person responsible for the simulations in this simulation round if not the main contact person', max_length=500, null=True, verbose_name='Responsible person'),
        ),
    ]
