# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0046_auto_20170117_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture',
            name='calibrated_values',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Calibrated values'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='co2_effects',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='CO2 Effects'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='criteria_for_evaluation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Criteria for evaluation (validation)'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='crop_cultivars',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Crop cultivars'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='crop_phenology',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Crop phenology'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='crop_residue',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Crop residue'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='crops',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Crops'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='evapo_transpiration',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Evapo-transpiration'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='fertilizer_application',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Fertilizer application'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='initial_crop_residue',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Initial crop residue'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='initial_soil_C_and_OM',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Initial soil C and OM'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='initial_soil_nitrate_and_ammonia',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Initial soil nitrate and ammonia'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='initial_soil_water',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Initial soil water'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='irrigation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Irrigation'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='land_coverage',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Land cover'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='lead_area_development',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Lead area development'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='light_interception',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Light interception'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='light_utilization',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Light utilization'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='output_variable_and_dataset',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Output variable and dataset for calibration validation'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='parameters_number_and_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Parameters, number and description'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='planting_date_decision',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Planting date decision'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='planting_density',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Planting density'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='root_distribution_over_depth',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Root distribution over depth'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='soil_CN_modeling',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Soil CN modeling'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='spatial_scale_of_calibration_validation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Spatial scale of calibration/validation'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='stresses_involved',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Stresses involved'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='temporal_scale_of_calibration_validation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temporal scale of calibration/validation'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='type_of_heat_stress',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Type of heat stress'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='type_of_water_stress',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Type of water stress'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='water_dynamics',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Water dynamics'),
        ),
        migrations.AlterField(
            model_name='agriculture',
            name='yield_formation',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Yield formation'),
        ),
        migrations.AlterField(
            model_name='baseimpactmodel',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='This short description should assist other researchers in briefly describing the model in a paper.', null=True, verbose_name='Short model description'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='closed_energy_balance',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='co2_effects',
            field=models.TextField(blank=True, default='', null=True, verbose_name='CO2 effects'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='considerations',
            field=models.TextField(blank=True, default='', help_text='Things to consider, when calculating basic variables such as GPP, NPP, RA, RH from the model.', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='dynamic_vegetation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='evapotranspiration_approach',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Evapo-transpiration approach'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='heat_stress',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='latent_heat',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='light_interception',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='light_utilization',
            field=models.TextField(blank=True, default='', help_text='photosynthesis, RUE-approach?', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='list_of_pfts',
            field=models.TextField(blank=True, default='', help_text='Provide a list of PFTs using the folllowing format: [pft1_long_name] ([pft1_short_name]); [pft2_long_name] ([pft2_short_name]). Include long name in brackets if no short name is available.', null=True, verbose_name='List of PFTs'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_age',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_drought',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Drought'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_fire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Fire'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_insects',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Insects'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_remarks',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_stochastic_random_disturbance',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Stochastic random disturbance'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_storm',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Storm'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_comments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_fire',
            field=models.TextField(blank=True, default='', help_text='Indicate whether the model includes fire, and how the model accounts for the fluxes, i.e. what is the fate of the biomass? E.g. directly to atmsphere or let it go to other pool', null=True, verbose_name='Fire'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_harvest',
            field=models.TextField(blank=True, default='', help_text='Indicate whether the model includes harvest, and how the model accounts for the fluxes, i.e. what is the fate of the biomass? E.g. directly to atmsphere or let it go to other pool. 1: crops, 2: harvest from forest management, 3: harvest from grassland management.', null=True, verbose_name='Harvest'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_landuse_change',
            field=models.TextField(blank=True, default='', help_text='Indicate whether the model includes land-use change (e.g. deforestation harvest and otherland-use changes), and how the model accounts for the fluxes, i.e. what is the fate of the biomass? e.g. directly to atmsphere or let it go to other pool', null=True, verbose_name='Land-use change'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nbp_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other processes'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='nitrogen_limitation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='output',
            field=models.TextField(blank=True, default='', help_text='Is output (e.g. PFT cover) written out per grid-cell area or per land and water area within a grid cell, or land only?', null=True, verbose_name='Output format'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='output_per_pft',
            field=models.TextField(blank=True, default='', help_text='Is output per PFT per unit area of that PFT, i.e. requiring weighting by the fractional coverage of each PFT to get the gridbox average?', null=True, verbose_name='Output per PFT?'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='permafrost',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='pfts_comments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='phenology',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='root_distribution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Root distribution over depth'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='rooting_depth_differences',
            field=models.TextField(blank=True, default='', help_text='Including how it changes', null=True, verbose_name='Differences in rooting depth'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='sensible_heat',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='soil_moisture_surface_temperature_coupling',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Coupling/feedback between soil moisture and surface temperature'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='water_stress',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='energy',
            name='bioenergy_supply_costs',
            field=models.TextField(blank=True, default='', help_text='Include information on the functional forms and the data sources for deriving the supply curves', null=True, verbose_name='Bioenergy supply costs'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='biomass_types',
            field=models.TextField(blank=True, default='', help_text='1st generation, 2nd generation, residues...', null=True, verbose_name='Biomass types'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='data_format_for_input',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Data format for input'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='factor_definition_and_calculation',
            field=models.TextField(blank=True, default='', help_text='Are these endogenous or exogenous to the model?', null=True, verbose_name='Definition and calculation of variable potential and load factor'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='impact_types_energy_demand',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Energy demand (heating & cooling)'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='impact_types_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other (agriculture, infrastructure, adaptation)'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='impact_types_temperature_effects_on_thermal_power',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temperature effects on thermal power'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='impact_types_water_scarcity_impacts',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Water scarcity impacts'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='impact_types_weather_effects_on_renewables',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Weather effects on renewables'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='maximum_potential_assumption',
            field=models.TextField(blank=True, default='', help_text='Which information source is used?', null=True, verbose_name='Maximum potential assumption'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='model_type',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Model type'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='output_economics',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Economics'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='output_energy_demand',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Energy demand (heating & cooling)'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='output_energy_supply',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Energy supply'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='output_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other (agriculture, infrastructure, adaptation)'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='output_water_scarcity',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Water scarcity'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='response_function_of_energy_demand_to_HDD_CDD',
            field=models.TextField(blank=True, default='', help_text='Including equations where appropriate', null=True, verbose_name='Response function of energy demand to HDD/CDD'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='socioeconomic_input',
            field=models.TextField(blank=True, default='', help_text='Are SSP storylines implemented, or just GDP and population scenarios?', null=True, verbose_name='Socio-economic input'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='temporal_extent',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temporal extent'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='temporal_resolution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temporal resolution'),
        ),
        migrations.AlterField(
            model_name='energy',
            name='variables_not_directly_from_GCMs',
            field=models.TextField(blank=True, default='', help_text='How are these calculated (including equations)?', null=True, verbose_name='Variables not directly from GCMs'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='closed_energy_balance',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='co2_effects',
            field=models.TextField(blank=True, default='', null=True, verbose_name='CO2 effects'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='considerations',
            field=models.TextField(blank=True, default='', help_text='Things to consider, when calculating basic variables such as GPP, NPP, RA, RH from the model.', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='dynamic_vegetation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='evapotranspiration_approach',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Evapo-transpiration approach'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='heat_stress',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='latent_heat',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='light_interception',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='light_utilization',
            field=models.TextField(blank=True, default='', help_text='photosynthesis, RUE-approach?', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='list_of_pfts',
            field=models.TextField(blank=True, default='', help_text='Provide a list of PFTs using the folllowing format: [pft1_long_name] ([pft1_short_name]); [pft2_long_name] ([pft2_short_name]). Include long name in brackets if no short name is available.', null=True, verbose_name='List of PFTs'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_age',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_drought',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Drought'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_fire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Fire'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_insects',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Insects'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_remarks',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_stochastic_random_disturbance',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Stochastic random disturbance'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_storm',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Storm'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='nbp_comments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='nbp_fire',
            field=models.TextField(blank=True, default='', help_text='Indicate whether the model includes fire, and how the model accounts for the fluxes, i.e. what is the fate of the biomass? E.g. directly to atmsphere or let it go to other pool', null=True, verbose_name='Fire'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='nbp_harvest',
            field=models.TextField(blank=True, default='', help_text='Indicate whether the model includes harvest, and how the model accounts for the fluxes, i.e. what is the fate of the biomass? E.g. directly to atmsphere or let it go to other pool. 1: crops, 2: harvest from forest management, 3: harvest from grassland management.', null=True, verbose_name='Harvest'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='nbp_landuse_change',
            field=models.TextField(blank=True, default='', help_text='Indicate whether the model includes land-use change (e.g. deforestation harvest and otherland-use changes), and how the model accounts for the fluxes, i.e. what is the fate of the biomass? e.g. directly to atmsphere or let it go to other pool', null=True, verbose_name='Land-use change'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='nbp_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other processes'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='nitrogen_limitation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='output',
            field=models.TextField(blank=True, default='', help_text='Is output (e.g. PFT cover) written out per grid-cell area or per land and water area within a grid cell, or land only?', null=True, verbose_name='Output format'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='output_per_pft',
            field=models.TextField(blank=True, default='', help_text='Is output per PFT per unit area of that PFT, i.e. requiring weighting by the fractional coverage of each PFT to get the gridbox average?', null=True, verbose_name='Output per PFT?'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='permafrost',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='pfts_comments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='phenology',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='root_distribution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Root distribution over depth'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='rooting_depth_differences',
            field=models.TextField(blank=True, default='', help_text='Including how it changes', null=True, verbose_name='Differences in rooting depth'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='sensible_heat',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='forests',
            name='soil_moisture_surface_temperature_coupling',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Coupling/feedback between soil moisture and surface temperature'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='water_stress',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='download_instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='inputdatainformation',
            name='soil_dataset',
            field=models.TextField(blank=True, default='', help_text='HWSD or GSWP3 were provided', null=True, verbose_name='Soil dataset'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='defining_features',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Defining features'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='fishbase_used_for_mass_length_conversion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Is FishBase used for mass-length conversion?'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='spatial_dispersal_included',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Spatial dispersal included'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='spatial_resolution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Spatial resolution'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='spatial_scale',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Spatial scale'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='taxonomic_scope',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Taxonomic scope'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='temporal_resolution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temporal resolution'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='temporal_scale',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temporal scale'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsglobal',
            name='vertical_resolution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Vertical resolution'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='defining_features',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Defining features'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='fishbase_used_for_mass_length_conversion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Is FishBase used for mass-length conversion?'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='spatial_dispersal_included',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Spatial dispersal included'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='spatial_resolution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Spatial resolution'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='spatial_scale',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Spatial scale'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='taxonomic_scope',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Taxonomic scope'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='temporal_resolution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temporal resolution'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='temporal_scale',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Temporal scale'),
        ),
        migrations.AlterField(
            model_name='marineecosystemsregional',
            name='vertical_resolution',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Vertical resolution'),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='anything_else',
            field=models.TextField(blank=True, default='', help_text='Anything else necessary to reproduce and/or understand the simulation output', null=True, verbose_name='Additional comments'),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='exceptions_to_protocol',
            field=models.TextField(blank=True, default='', help_text='Any settings prescribed by the ISIMIP protocol that were overruled when runing the model', null=True, verbose_name='Exceptions'),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='extreme_events',
            field=models.TextField(blank=True, default='', help_text='Key challenges for this model in reproducing impacts of extreme events', null=True, verbose_name='Key challenges'),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='management',
            field=models.TextField(blank=True, default='', help_text='Specific management and autonomous adaptation measures applied. E.g. varying sowing dates in crop models, dbh-related harvesting in forest models.', null=True),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='natural_vegetation_cover_dataset',
            field=models.TextField(blank=True, default='', help_text='Dataset used if natural vegetation cover is prescribed', null=True),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='natural_vegetation_dynamics',
            field=models.TextField(blank=True, default='', help_text='Description of how natural vegetation is simulated dynamically where relevant', null=True),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='natural_vegetation_partition',
            field=models.TextField(blank=True, default='', help_text='How areas covered by different types of natural vegetation are partitioned', null=True),
        ),
        migrations.AlterField(
            model_name='otherinformation',
            name='spin_up_design',
            field=models.TextField(blank=True, default='', help_text='Including the length of the spin up, the CO2 concentration used, and any deviations from the spin-up procedure defined in the protocol', null=True, verbose_name='Spin-up design'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='calibration_catchments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='How many catchments were callibrated?'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='calibration_dataset',
            field=models.TextField(blank=True, default='', help_text='E.g. WFD, GSWP3', null=True, verbose_name='Which dataset was used for calibration?'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='calibration_years',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Which years were used for calibration?'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='dams_reservoirs',
            field=models.TextField(blank=True, default='', help_text='Describe how are dams and reservoirs are implemented', null=True, verbose_name='Dam and reservoir implementation'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='land_use',
            field=models.TextField(blank=True, default='', help_text='Which land-use change effects are included?', null=True, verbose_name='Land-use change effects'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='methods_evapotranspiration',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Potential evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='methods_snowmelt',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Snow melt'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='routing',
            field=models.TextField(blank=True, default='', help_text='How is runoff routed?', null=True, verbose_name='Runoff routing'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='routing_data',
            field=models.TextField(blank=True, default='', help_text='Which routing data are used?', null=True),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='soil_layers',
            field=models.TextField(blank=True, default='', help_text='How many soil layers are used? Which qualities do they have?', null=True),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='technological_progress',
            field=models.TextField(blank=True, default='', help_text='Does the model account for GDP changes and technological progress? If so, how are these integrated into the runs?', null=True),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='vegetation_representation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='How is vegetation represented?'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='water_sectors',
            field=models.TextField(blank=True, default='', help_text='For the global-water-model varsoc and pressoc runs, which water sectors were included? E.g. irrigation, domestic, manufacturing, electricity, livestock.', null=True, verbose_name='Water-use sectors'),
        ),
        migrations.AlterField(
            model_name='waterglobal',
            name='water_use',
            field=models.TextField(blank=True, default='', help_text='Which types of water use are included in the model?', null=True, verbose_name='Water-use types'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='calibration_catchments',
            field=models.TextField(blank=True, default='', null=True, verbose_name='How many catchments were callibrated?'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='calibration_dataset',
            field=models.TextField(blank=True, default='', help_text='E.g. WFD, GSWP3', null=True, verbose_name='Which dataset was used for calibration?'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='calibration_years',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Which years were used for calibration?'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='dams_reservoirs',
            field=models.TextField(blank=True, default='', help_text='Describe how are dams and reservoirs are implemented', null=True, verbose_name='Dam and reservoir implementation'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='land_use',
            field=models.TextField(blank=True, default='', help_text='Which land-use change effects are included?', null=True, verbose_name='Land-use change effects'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='methods_evapotranspiration',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Potential evapotranspiration'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='methods_snowmelt',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Snow melt'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='routing',
            field=models.TextField(blank=True, default='', help_text='How is runoff routed?', null=True, verbose_name='Runoff routing'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='routing_data',
            field=models.TextField(blank=True, default='', help_text='Which routing data are used?', null=True),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='soil_layers',
            field=models.TextField(blank=True, default='', help_text='How many soil layers are used? Which qualities do they have?', null=True),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='technological_progress',
            field=models.TextField(blank=True, default='', help_text='Does the model account for GDP changes and technological progress? If so, how are these integrated into the runs?', null=True),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='vegetation_representation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='How is vegetation represented?'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='water_sectors',
            field=models.TextField(blank=True, default='', help_text='For the global-water-model varsoc and pressoc runs, which water sectors were included? E.g. irrigation, domestic, manufacturing, electricity, livestock.', null=True, verbose_name='Water-use sectors'),
        ),
        migrations.AlterField(
            model_name='waterregional',
            name='water_use',
            field=models.TextField(blank=True, default='', help_text='Which types of water use are included in the model?', null=True, verbose_name='Water-use types'),
        ),
    ]
