# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


def set_old_data(apps, schema_editor):
    InputDataModel = apps.get_model('climatemodels', 'InputData')
    for input_data in InputDataModel.objects.all():
        if input_data.old_scenario:
            input_data.scenario.add(input_data.old_scenario)
        if input_data.old_simulation_round:
            input_data.simulation_round.add(input_data.old_simulation_round)
        input_data.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0049_auto_20170119_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='scenario',
            field=models.ManyToManyField(blank=True, related_name='scenarios', to='climatemodels.Scenario'),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='simulation_round',
            field=models.ManyToManyField(blank=True, related_name='simulationrounds', to='climatemodels.SimulationRound'),
        ),
        migrations.RunPython(
            set_old_data
        ),
    ]
