# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def create_sectors(apps, schema_editor):
    SectorModel = apps.get_model('climatemodels', 'Sector')
    SectorModel.objects.get_or_create(name='Agriculture', slug=slugify('Agriculture'))
    SectorModel.objects.get_or_create(name='Agro-Economic Modelling', slug=slugify('Agro-Economic Modelling'))
    SectorModel.objects.get_or_create(name='Biodiversity', slug=slugify('Biodiversity'))
    SectorModel.objects.get_or_create(name='Biomes', slug=slugify('Biomes'))
    SectorModel.objects.get_or_create(name='Coastal Infrastructure', slug=slugify('Coastal Infrastructure'))
    SectorModel.objects.get_or_create(name='Computable General Equilibrium Modelling', slug=slugify('Computable General Equilibrium Modelling'))
    SectorModel.objects.get_or_create(name='Energy', slug=slugify('Energy'))
    SectorModel.objects.get_or_create(name='Forests', slug=slugify('Forests'))
    SectorModel.objects.get_or_create(name='Health', slug=slugify('Health'))
    SectorModel.objects.get_or_create(name='Marine Ecosystems and Fisheries (global)', slug=slugify('Marine Ecosystems and Fisheries (global)'))
    SectorModel.objects.get_or_create(name='Marine Ecosystems and Fisheries (regional)', slug=slugify('Marine Ecosystems and Fisheries (regional)'))
    SectorModel.objects.get_or_create(name='Permafrost', slug=slugify('Permafrost'))
    SectorModel.objects.get_or_create(name='Water (global)', slug=slugify('Water (global)'))
    SectorModel.objects.get_or_create(name='Water (regional)', slug=slugify('Water (regional)'))


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0051_auto_20170119_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Sectors',
            },
        ),
        migrations.AlterModelOptions(
            name='baseimpactmodel',
            options={},
        ),
        migrations.RenameField(
            model_name='baseimpactmodel',
            old_name='sector',
            new_name='sector_old',
        ),
        migrations.RunPython(
            create_sectors
        ),
    ]
