# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0053_auto_20170119_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputdata',
            old_name='sector',
            new_name='sector_old',
        ),
        migrations.RemoveField(
            model_name='baseimpactmodel',
            name='sector_old',
        ),
    ]
