# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_sectors(apps, schema_editor):
    SectorModel = apps.get_model('climatemodels', 'Sector')
    OutputDataModel = apps.get_model('climatemodels', 'OutputData')
    for od in OutputDataModel.objects.all():
        od.sector = SectorModel.objects.get(name=od.sector_old)
        od.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0054_auto_20170119_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdata',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='climatemodels.Sector'),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_sectors
        ),
    ]
