# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 12:48
from __future__ import unicode_literals

from django.db import migrations


def set_sectors(apps, schema_editor):
    SectorModel = apps.get_model('climatemodels', 'Sector')
    OutputDataModel = apps.get_model('climatemodels', 'OutputData')
    for od in OutputDataModel.objects.all():
        od.sector = SectorModel.objects.get(name=od.sector_old)
        od.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0055_outputdata_sector'),
    ]

    operations = [
        migrations.RunPython(
            set_sectors
        ),
        migrations.RemoveField(
            model_name='outputdata',
            name='sector_old',
        ),
    ]
