# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0057_sector_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ImpactModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sector',
            name='class_name',
            field=models.CharField(choices=[('GenericSector', 'Generic Sector'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy'), ('WaterGlobal', 'Water (global)'), ('WaterRegional', 'Water (regional)'), ('Biomes', 'Biomes'), ('Forests', 'Forests'), ('MarineEcosystemsGlobal', 'Marine Ecosystems and Fisheries (global)'), ('MarineEcosystemsRegional', 'Marine Ecosystems and Fisheries (regional)'), ('Biodiversity', 'Biodiversity'), ('Health', 'Health'), ('CoastalInfrastructure', 'Coastal Infrastructure'), ('Permafrost', 'Permafrost'), ('ComputableGeneralEquilibriumModelling', 'Computable General Equilibrium Modelling'), ('AgroEconomicModelling', 'Agro-Economic Modelling')], default='GenericSector', max_length=500),
        ),
    ]
