# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0058_auto_20170119_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorInformationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('help_text', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SectorInformationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.Sector')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Sector information groups',
            },
        ),
        migrations.AddField(
            model_name='sectorinformationfield',
            name='information_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.SectorInformationGroup'),
        ),
    ]
