# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0060_auto_20170119_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorinformationfield',
            name='information_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='climatemodels.SectorInformationGroup'),
        ),
        migrations.AlterField(
            model_name='sectorinformationfield',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='sectorinformationfield',
            unique_together=set([('name', 'information_group')]),
        ),
    ]
