# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 09:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0061_auto_20170119_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsector',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
