# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0062_genericsector_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericsector',
            options={'verbose_name': 'Generic sector'},
        ),
        migrations.AddField(
            model_name='sectorinformationfield',
            name='identifier',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectorinformationgroup',
            name='identifier',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
