# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0065_auto_20170120_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdatainformation',
            name='socioeconomic_input_variables',
        ),
        migrations.RemoveField(
            model_name='inputdatainformation',
            name='soil_dataset',
        ),
    ]
