# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0069_auto_20170120_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputdata',
            name='experiments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outputdata',
            name='simulation_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='climatemodels.SimulationRound'),
        ),
    ]
