# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0071_auto_20170123_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputdata',
            name='data_source',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='specification',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
