# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0073_auto_20170124_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdatainformation',
            name='climate_data_sets',
        ),
    ]
