# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0074_remove_inputdatainformation_climate_data_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='has_sector_specific_values',
            field=models.BooleanField(default=True),
        ),
    ]
