# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0075_sector_has_sector_specific_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdatainformation',
            name='climate_variables',
            field=models.ManyToManyField(blank=True, help_text='Which of the climate input variables provided was used by your model?', to='climatemodels.ClimateVariable', verbose_name='Climate variables'),
        ),
        migrations.AlterField(
            model_name='inputdatainformation',
            name='climate_variables_info',
            field=models.TextField(blank=True, help_text='Including how variables were derived that were not included in the ISIMIP input data', verbose_name='Additional information about input variables'),
        ),
    ]
