# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0076_auto_20170125_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculture',
            name='lead_area_development',
            field=models.TextField(blank=True, default='', help_text='Methods for model calibration and validation', null=True, verbose_name='Leaf area development'),
        ),
    ]
