# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 10:52
from __future__ import unicode_literals

from django.db import migrations


def set_user_profile(apps, schema_editor):
    BaseImpactModel = apps.get_model('climatemodels', 'BaseImpactModel')
    UserProfile = apps.get_model('contrib', 'UserProfile')
    for base_impact_model in BaseImpactModel.objects.all():
        for owner in base_impact_model.owners.all():
            if not hasattr(owner, 'userprofile'):
                UserProfile.objects.create(user=owner)
            owner.userprofile.owner.add(base_impact_model)
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0077_auto_20170301_1209'),
    ]

    operations = [
        migrations.RunPython(
            set_user_profile
        ),
    ]
