# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0079_set_contact_persons_20170307_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomes',
            name='list_of_pfts',
            field=models.TextField(blank=True, default='', help_text='Provide a list of PFTs using the folllowing format: [pft1_long_name] ([pft1_short_name]); [pft2_long_name] ([pft2_short_name]). Include long name in brackets if no short name is available.', null=True, verbose_name='List of species / PFTs'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='list_of_pfts',
            field=models.TextField(blank=True, default='', help_text='Provide a list of PFTs using the folllowing format: [pft1_long_name] ([pft1_short_name]); [pft2_long_name] ([pft2_short_name]). Include long name in brackets if no short name is available.', null=True, verbose_name='List of species / PFTs'),
        ),
    ]
