# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0082_auto_20170614_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputdata',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='outputdata',
            name='simulation_round',
        ),
    ]
