# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0084_inputdata_protocol_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmodel',
            name='version',
            field=models.CharField(blank=True, help_text='The model version with which these simulations were run. Please indicate if the model version used for ISIMIP2b can be evaluated based on comparison of the ISIMIP2a runs with observed impacts.', max_length=500, null=True, verbose_name='Model version'),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='protocol_relation',
            field=models.CharField(choices=[('P', 'Protocol'), ('S', 'Supplementary')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='inputdata',
            name='variables',
            field=models.ManyToManyField(blank=True, help_text='The variables are filtered based on the data type. To see variables of a different data type, please change and save data type first.', to='climatemodels.ClimateVariable'),
        ),
        migrations.AlterField(
            model_name='outputdata',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ImpactModel'),
        ),
    ]
