# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import isi_mip.climatemodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0085_auto_20180215_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment1', models.FileField(upload_to=isi_mip.climatemodels.models.impact_model_path)),
                ('attachment2', models.FileField(upload_to=isi_mip.climatemodels.models.impact_model_path)),
                ('attachment3', models.FileField(upload_to=isi_mip.climatemodels.models.impact_model_path)),
                ('attachment4', models.FileField(upload_to=isi_mip.climatemodels.models.impact_model_path)),
                ('attachment5', models.FileField(upload_to=isi_mip.climatemodels.models.impact_model_path)),
                ('impact_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='climatemodels.ImpactModel')),
            ],
        ),
    ]
