# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('climatemodels', '0085_auto_20180215_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPublicationConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email_text', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('impact_model', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation', to='climatemodels.ImpactModel')),
            ],
            options={
                'verbose_name_plural': 'Data publication confirmations',
                'verbose_name': 'Data publication confirmation',
            },
        ),
    ]
