# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0087_datapublicationconfirmation_confirmed_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapublicationconfirmation',
            name='email_text',
            field=models.TextField(help_text='Please insert information on the experiments that are to be published here (required).'),
        ),
    ]
