# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 15:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import isi_mip.climatemodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0088_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment3',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment4',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])]),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment5',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])]),
        ),
    ]
