# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-26 12:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import isi_mip.climatemodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0092_auto_20181219_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment1_description',
            field=models.TextField(blank=True, null=True, verbose_name='Attachment description'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment2_description',
            field=models.TextField(blank=True, null=True, verbose_name='Attachment description'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment3_description',
            field=models.TextField(blank=True, null=True, verbose_name='Attachment description'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment4_description',
            field=models.TextField(blank=True, null=True, verbose_name='Attachment description'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment5_description',
            field=models.TextField(blank=True, null=True, verbose_name='Attachment description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment3',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment4',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])], verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment5',
            field=models.FileField(blank=True, null=True, upload_to=isi_mip.climatemodels.models.impact_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'csv'])], verbose_name='Attachment'),
        ),
    ]
