# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-04 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0093_auto_20190326_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='forests',
            name='assimilation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Assimilation'),
        ),
        migrations.AddField(
            model_name='forests',
            name='carbon_allocation',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Carbon allocation'),
        ),
        migrations.AddField(
            model_name='forests',
            name='carbon_nitrogen_balance',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Carbon/Nitrogen balance'),
        ),
        migrations.AddField(
            model_name='forests',
            name='feedbacks_considered',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Are feedbacks considered that reflect the influence of changing carbon state variables on the other system components and driving data (i.e. Growth (leaf area), light, temperature, water availability, nutrient availability)?'),
        ),
        migrations.AddField(
            model_name='forests',
            name='regeneration_planting',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Regeneration/planting'),
        ),
        migrations.AddField(
            model_name='forests',
            name='respiration',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Respiration'),
        ),
        migrations.AddField(
            model_name='forests',
            name='soil_water_balance',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Soil water balance'),
        ),
        migrations.AddField(
            model_name='forests',
            name='stochastic_element',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Is there any stochastic element in your model (e.g. in the management or mortality submodel) that will lead to slightly different results if the model is re-run, even though all drivers etc. remain the same?'),
        ),
        migrations.AddField(
            model_name='forests',
            name='upload_parameter_list',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Please upload a list of your parameters as an attachment (Section 7). The list should include species-specific parameters and other parameters not depending on initialization data including the following information: short name, long name, short explanation, unit, value, see here for an example (http://www.pik-potsdam.de/4c/web_4c/theory/parameter_table_0514.pdf)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment1_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment2_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment3_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment4_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attachment5_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='biomes',
            name='mortality_age',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Age/Senescence'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='initialize_model',
            field=models.TextField(blank=True, default='', null=True, verbose_name='How did you initialize your model, e.g. using Individual tree dbh and height or stand basal area? How do you initialize soil conditions?'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='mortality_age',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Age/Senescence'),
        ),
        migrations.AlterField(
            model_name='forests',
            name='soil_depth',
            field=models.TextField(blank=True, default='', null=True, verbose_name='What is the soil depth you assumed for each site and how many soil layers (including their depths) do you assume in each site? Please upload a list of the soil depth and soil layers your model assumes for each site as an attachment (Section 7).'),
        ),
    ]
