# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0095_auto_20190408_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='folder_name',
            field=models.CharField(default='folder', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impactmodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
