# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0097_auto_20190119_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseimpactmodel',
            name='drkz_folder_name',
            field=models.CharField(default='name', max_length=500, verbose_name='DKRZ folder name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sector',
            name='drkz_folder_name',
            field=models.CharField(max_length=500, verbose_name='DKRZ folder name'),
        ),
    ]
