# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-19 05:03
from __future__ import unicode_literals

from django.db import migrations


def set_drkz_folder_name(apps, schema_editor):
    BaseImpactModel = apps.get_model('climatemodels', 'BaseImpactModel')
    for model in BaseImpactModel.objects.all():
        model.drkz_folder_name = model.name
        model.save()


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0098_auto_20190119_0603'),
    ]

    operations = [
        migrations.RunPython(set_drkz_folder_name),
    ]
