# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0099_auto_20190119_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodel',
            name='model_output_license',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Model Output License'),
        ),
        migrations.AlterField(
            model_name='baseimpactmodel',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='This information applies to all modeling rounds. Please do not erase this information, just add when necessary. This short description should assist other researchers in getting an understanding of your model, including the main differences between model versions used for different ISIMIP simulation rounds.', null=True, verbose_name='Short model description'),
        ),
    ]
