# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0100_auto_20190408_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmodel',
            name='simulation_round_specific_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Simulation round specific description'),
        ),
    ]
