# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0101_impactmodel_simulation_round_specific_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactmodel',
            name='model_output_license',
        ),
        migrations.AlterField(
            model_name='baseimpactmodel',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='This short description should assist other researchers in getting an understanding of your model, including the main differences between model versions used for different ISIMIP simulation rounds.', null=True, verbose_name='Short model description (all rounds)'),
        ),
    ]
