# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatemodels', '0102_auto_20190408_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='forests',
            name='minimum_diameter_tree',
            field=models.TextField(blank=True, default='', null=True, verbose_name='What is the minimum diameter at which a „tree is considered a tree“? and is there a similar threshold for the minimum harvestable diameter?'),
        ),
        migrations.AddField(
            model_name='forests',
            name='model_historically_calibrated',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Has your model been "historically calibrated" to any of the sites you simulated? e.g. has the site been used for model testing during model development?'),
        ),
    ]
