# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='anchor',
            field=models.CharField(blank=True, help_text='A specific anchor to scroll to.', max_length=500, null=True),
        ),
    ]
