# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterSettings',
            new_name='FooterLinks',
        ),
        migrations.RenameModel(
            old_name='HeaderSettings',
            new_name='HeaderLinks',
        ),
    ]
