# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='subject',
            field=models.CharField(default='[ISIMIP] Registration invitation for impact-model database', help_text='Invitation subject', max_length=500),
        ),
    ]
