# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 12:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170118_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlink',
            name='menu_items',
            field=wagtail.wagtailcore.fields.StreamField((('jump_link', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('link', wagtail.wagtailcore.blocks.URLBlock())))), ('page_link', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock()))))), blank=True, null=True),
        ),
    ]
