# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 14:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_headerlink_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlink',
            name='menu_items',
            field=wagtail.core.fields.StreamField((('jump_link', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.CharBlock())))), ('page_link', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock()))))), blank=True, null=True),
        ),
    ]
