# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_confirmdatapublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmdatapublication',
            name='subject',
            field=models.CharField(default='[ISIMIP] Confirm data', help_text='Invitation subject', max_length=500),
        ),
    ]
