# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180215_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmdatapublication',
            name='body',
            field=models.TextField(default='Dear {model_contact_person},\n\nwe have completed the basic quality check for the {simulation_round} simulation data you uploaded recently. You can find the quality-checked data, which is now visible to all ISIMIP participants, in the relevant directory on the DKRZ server:\n/work/bb0820/ISIMIP/ISIMIP2b/OutputData/{sector}/{impact_model}/… The data cover the experiments:\n\n{custom_text}\n\nWe are now ready to copy this data to the ISIMIP node of the ESGF server at esg.pik-potsdam.de, as stated in the terms of use by following the instructions on the data confirmation page:\n\n{data_confirm_page}\n\nBest wishes from the ISIMIP management team.\n\n', help_text='You can use the following tokens in the email template: {model_contact_person}, {simulation_round}, {sector}. {impact_model}'),
        ),
        migrations.AlterField(
            model_name='confirmdatapublication',
            name='subject',
            field=models.CharField(default='[ISIMIP] Data confirmation request', help_text='Invitation subject', max_length=500),
        ),
    ]
