# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('core', '0009_auto_20180221_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPublicationConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='[ISIMIP] Data confirmation', help_text='Data publication confirmation subject', max_length=500)),
                ('body', models.TextField(help_text='You can use the following tokens in the email template: {{model_contact_person}}, {{simulation_round}}, {{sector}}, {{impact_model}}, {{data_confirm_link}}, {{custom_text}}')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataPublicationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='[ISIMIP] Data confirmation request', help_text='Data publication request subject', max_length=500)),
                ('body', models.TextField(help_text='You can use the following tokens in the email template: {{model_contact_person}}, {{simulation_round}}, {{sector}}, {{impact_model}}, {{data_confirm_link}}, {{custom_text}}')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='confirmdatapublication',
            name='site',
        ),
        migrations.DeleteModel(
            name='ConfirmDataPublication',
        ),
    ]
