# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180221_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapublicationconfirmation',
            name='body',
            field=models.TextField(help_text='You can use the following tokens in the email template: {{model_contact_person}}, {{simulation_round}}, {{impact_model_name}}, {{custom_text}}, {{license}}'),
        ),
        migrations.AlterField(
            model_name='datapublicationrequest',
            name='body',
            field=models.TextField(help_text='You can use the following tokens in the email template: {{model_contact_person}}, {{simulation_round}}, {{sector}}, {{impact_model_name}}, {{data_confirmation_link}}, {{custom_text}}'),
        ),
    ]
