# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180221_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapublicationrequest',
            name='body',
            field=models.TextField(help_text='You can use the following tokens in the email template: {{model_contact_person}}, {{simulation_round}}, {{sector}}, {{sector_drkz_folder_name}}, {{impact_model_name}}, {{impact_model_drkz_folder_name}}, {{data_confirmation_link}}, {{custom_text}}'),
        ),
    ]
